### ISSUE TITLE
Can you add arm64 build?

### ISSUE THREAD

**Issue by MakiseKurisu** [mikolatero/docker-vlmcsd#4]
It is quite convenient to run those services on ARM single board computers now.

**Comment by mikolatero** [comment]
Of course! It's something I haven't needed so far but it's a very good idea. I'll get on it and I'll comment again when I upload the arm tags.

**Comment by mikolatero** [comment]
@MakiseKurisu  Done!

The following archs are now available on dockerhub:

 - i386
 - amd64
 - armv6
 - armv7
 - arm64

I don't have any raspberry or arm device nearby right now, could you confirm that it works if you try it?

Thank you.

**Comment by MakiseKurisu** [comment]
Wow amazing speed! Got it running on my Raspberry Pi 3 and tested with vlmcs. Thank you!

**Comment by Schmandre** [comment]
@MakiseKurisu How did you get the whole thing to work on the Pi? Here is my docker-compose.yml:

`version: '3'
services:
  vlmcsd:
    image: mogeko/vlmcsd:latest
    container_name: kms
    ports:
      - 1688:1688
    restart: unless-stopped`
    
When I start the container, I get the message permanently: `standard_init_linux.go:228: exec user process caused: exec format error`

On another system it runs without problems with this configuration. Only on the Pi4 apparently not :(
