### ISSUE TITLE
raspberry pi 3b arm

### ISSUE THREAD

**Issue by jsavargas** [mikolatero/docker-vlmcsd#5]
does not work on a raspberry pi 3b arm
I am doing something wrong?

![image](https://user-images.githubusercontent.com/6886410/147627804-2f774b30-2199-4037-bea1-01d1b33b925d.png)
![image](https://user-images.githubusercontent.com/6886410/147627863-8a0399e8-7c4c-4757-8737-bbd9d15011bb.png)

**Comment by mikolatero** [comment]
Tested in Raspbian 11 with latest docker and works like a charm:

![image](https://user-images.githubusercontent.com/1868695/147760640-da274b4e-ab0f-4a0a-9682-b0a5dadff147.png)



Are you tried to read docker logs with: `docker logs vlmcsd` and see what is happening?
